name: bump_version

on:
  push:
    branches: [main]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Bump minor version
        run: |
          set -x
          git config --global user.name "p3zo"
          git config --global user.email "p3zo@users.noreply.github.com"
          git config --global pull.rebase false
          BRANCH=${GITHUB_REF#refs/heads/}
          pip install --no-cache-dir bumpversion
          git remote add p3zo https://${{ secrets.BOT_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git pull --no-edit p3zo $BRANCH
          bumpversion --tag --commit --commit-args="-a" minor
          git push --tags p3zo HEAD:$BRANCH
