name: increment_version
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: pre-commit/action@v2.0.2
      - name: Install bumpversion
        run: |
          python -m pip install --upgrade pip
          python -m pip install bumpversion
      - name: Bump minor version
        run: |
          bumpversion minor
